#!/bin/sh
# Xsetup - run as root before the login dialog appears

# Monitors
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --rate 180 --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal --rate 144

# Mouse DPI
xinput --set-prop 'pointer:''Logitech G203 LIGHTSYNC Gaming Mouse' 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 'pointer:''Logitech G203 LIGHTSYNC Gaming Mouse' 'libinput Accel Speed' 0.0

# Caps as Ctrl
setxkbmap -option caps:ctrl_modifier
setxkbmap us

xset r rate 400 40
