#!/bin/bash

# @raycast.schemaVersion 1
# @raycast.title PlanEstudios
# @raycast.mode silent
# @raycast.icon 🗓️
# @raycast.packageName Unnoba


open -a Preview /Users/koch/Workspace/unnoba/assets/img/planEstudios.png
